import type { Role } from "@/context/role-context"

export interface Member {
  id: string
  name: string
  email: string
  phone: string
  role: Role
  status: "active" | "inactive" | "alumni"
  joinDate: string
  avatar?: string
  department: string
  year: string
  tasksCompleted: number
  eventsAttended: number
  bio?: string
  linkedinURL?: string
}

export const MEMBER_STATUSES = [
  { value: "active", label: "Active", color: "bg-emerald-500/20 text-emerald-400" },
  { value: "inactive", label: "Inactive", color: "bg-slate-500/20 text-slate-400" },
  { value: "alumni", label: "Alumni", color: "bg-violet-500/20 text-violet-400" },
] as const

export const DEPARTMENTS = [
  "Computer Science",
  "Business Administration",
  "Engineering",
  "Arts & Media",
  "Health Sciences",
  "Mathematics",
  "Communications",
  "Political Science",
] as const

export const YEARS = ["1st Year", "2nd Year", "3rd Year", "4th Year", "Graduate"] as const

export const SEED_MEMBERS: Member[] = [
  {
    id: "m1",
    name: "Naeem Baig",
    email: "naeem.baig@yorku.ca",
    phone: "(416) 555-0101",
    role: "President",
    status: "active",
    joinDate: "2024-09-01",
    department: "Computer Science",
    year: "4th Year",
    tasksCompleted: 34,
    eventsAttended: 12,
    bio: "Passionate about building tech communities and leading innovative projects.",
  },
  {
    id: "m2",
    name: "Sarah Chen",
    email: "sarah.chen@yorku.ca",
    phone: "(416) 555-0102",
    role: "VP Internal",
    status: "active",
    joinDate: "2024-09-01",
    department: "Business Administration",
    year: "3rd Year",
    tasksCompleted: 28,
    eventsAttended: 10,
    bio: "Operations enthusiast with a knack for keeping teams on track.",
  },
  {
    id: "m3",
    name: "Marcus Johnson",
    email: "marcus.j@yorku.ca",
    phone: "(416) 555-0103",
    role: "VP Finance",
    status: "active",
    joinDate: "2024-09-15",
    department: "Business Administration",
    year: "4th Year",
    tasksCompleted: 22,
    eventsAttended: 8,
    bio: "Detail-oriented finance student with experience in non-profit budgeting.",
  },
  {
    id: "m4",
    name: "Priya Sharma",
    email: "priya.s@yorku.ca",
    phone: "(416) 555-0104",
    role: "VP Events",
    status: "active",
    joinDate: "2024-09-01",
    department: "Communications",
    year: "3rd Year",
    tasksCompleted: 19,
    eventsAttended: 15,
    bio: "Creative event planner who loves bringing people together.",
  },
  {
    id: "m5",
    name: "Alex Rivera",
    email: "alex.r@yorku.ca",
    phone: "(416) 555-0105",
    role: "VP External",
    status: "active",
    joinDate: "2024-10-01",
    department: "Political Science",
    year: "4th Year",
    tasksCompleted: 15,
    eventsAttended: 7,
    bio: "Skilled negotiator focused on building lasting partnerships.",
  },
  {
    id: "m6",
    name: "Jordan Lee",
    email: "jordan.l@yorku.ca",
    phone: "(416) 555-0106",
    role: "Marketing",
    status: "active",
    joinDate: "2024-09-20",
    department: "Arts & Media",
    year: "2nd Year",
    tasksCompleted: 31,
    eventsAttended: 9,
    bio: "Graphic designer and social media strategist.",
  },
  {
    id: "m7",
    name: "Emily Watson",
    email: "emily.w@yorku.ca",
    phone: "(416) 555-0107",
    role: "Executive",
    status: "active",
    joinDate: "2025-01-10",
    department: "Computer Science",
    year: "2nd Year",
    tasksCompleted: 12,
    eventsAttended: 6,
  },
  {
    id: "m8",
    name: "David Kim",
    email: "david.k@yorku.ca",
    phone: "(416) 555-0108",
    role: "Executive",
    status: "active",
    joinDate: "2025-01-10",
    department: "Engineering",
    year: "1st Year",
    tasksCompleted: 8,
    eventsAttended: 4,
  },
  {
    id: "m9",
    name: "Fatima Al-Hassan",
    email: "fatima.ah@yorku.ca",
    phone: "(416) 555-0109",
    role: "Executive",
    status: "active",
    joinDate: "2024-09-01",
    department: "Health Sciences",
    year: "3rd Year",
    tasksCompleted: 20,
    eventsAttended: 11,
  },
  {
    id: "m10",
    name: "Chris O'Brien",
    email: "chris.ob@yorku.ca",
    phone: "(416) 555-0110",
    role: "Administrator",
    status: "active",
    joinDate: "2024-09-01",
    department: "Computer Science",
    year: "4th Year",
    tasksCompleted: 45,
    eventsAttended: 14,
    bio: "Full-stack developer maintaining the club's digital infrastructure.",
  },
  {
    id: "m11",
    name: "Lisa Park",
    email: "lisa.p@yorku.ca",
    phone: "(416) 555-0111",
    role: "Executive",
    status: "inactive",
    joinDate: "2024-09-15",
    department: "Mathematics",
    year: "2nd Year",
    tasksCompleted: 5,
    eventsAttended: 2,
  },
  {
    id: "m12",
    name: "Ryan Thompson",
    email: "ryan.t@yorku.ca",
    phone: "(416) 555-0112",
    role: "VP Events",
    status: "alumni",
    joinDate: "2023-09-01",
    department: "Communications",
    year: "Graduate",
    tasksCompleted: 52,
    eventsAttended: 28,
    bio: "Former VP Events who helped establish the club's signature annual gala.",
  },
  {
    id: "m13",
    name: "Nina Patel",
    email: "nina.p@yorku.ca",
    phone: "(416) 555-0113",
    role: "Executive",
    status: "active",
    joinDate: "2025-01-15",
    department: "Business Administration",
    year: "1st Year",
    tasksCompleted: 3,
    eventsAttended: 2,
  },
  {
    id: "m14",
    name: "Tyler Wright",
    email: "tyler.w@yorku.ca",
    phone: "(416) 555-0114",
    role: "Executive",
    status: "active",
    joinDate: "2024-10-20",
    department: "Engineering",
    year: "3rd Year",
    tasksCompleted: 14,
    eventsAttended: 6,
  },
]
